// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_AmbilightUI_H
#define WINRT_AmbilightUI_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.250303.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.250303.1"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/AmbilightUI.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::AmbilightUI::IMainWindow> : produce_base<D, winrt::AmbilightUI::IMainWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::AmbilightUI
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::AmbilightUI::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::AmbilightUI::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::AmbilightUI::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
