
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Windows.Foundation.h>)
#include <winrt/Windows.Foundation.h>
#endif


namespace winrt::AmbilightUI::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::AmbilightUI::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView NavView()
        {
            return _NavView;
        }
        void NavView(::winrt::Microsoft::UI::Xaml::Controls::NavigationView value)
        {
            _NavView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock HeaderTextBlock()
        {
            return _HeaderTextBlock;
        }
        void HeaderTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _HeaderTextBlock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border PowerPanel()
        {
            return _PowerPanel;
        }
        void PowerPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _PowerPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border EffectsPanel()
        {
            return _EffectsPanel;
        }
        void EffectsPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _EffectsPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border MotionPanel()
        {
            return _MotionPanel;
        }
        void MotionPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _MotionPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border ColorPanel()
        {
            return _ColorPanel;
        }
        void ColorPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _ColorPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border MappingPanel()
        {
            return _MappingPanel;
        }
        void MappingPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _MappingPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border HardwarePanel()
        {
            return _HardwarePanel;
        }
        void HardwarePanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _HardwarePanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel SensorsPanel()
        {
            return _SensorsPanel;
        }
        void SensorsPanel(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _SensorsPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border AboutPanel()
        {
            return _AboutPanel;
        }
        void AboutPanel(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _AboutPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock GpuTempText()
        {
            return _GpuTempText;
        }
        void GpuTempText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _GpuTempText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar GpuTempProgressBar()
        {
            return _GpuTempProgressBar;
        }
        void GpuTempProgressBar(::winrt::Microsoft::UI::Xaml::Controls::ProgressBar value)
        {
            _GpuTempProgressBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock LdrValueText()
        {
            return _LdrValueText;
        }
        void LdrValueText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _LdrValueText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar LdrProgressBar()
        {
            return _LdrProgressBar;
        }
        void LdrProgressBar(::winrt::Microsoft::UI::Xaml::Controls::ProgressBar value)
        {
            _LdrProgressBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ComPortBox()
        {
            return _ComPortBox;
        }
        void ComPortBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ComPortBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox AuxModeBox()
        {
            return _AuxModeBox;
        }
        void AuxModeBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _AuxModeBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColorPicker AuxColorPicker()
        {
            return _AuxColorPicker;
        }
        void AuxColorPicker(::winrt::Microsoft::UI::Xaml::Controls::ColorPicker value)
        {
            _AuxColorPicker = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox TopLedBox()
        {
            return _TopLedBox;
        }
        void TopLedBox(::winrt::Microsoft::UI::Xaml::Controls::NumberBox value)
        {
            _TopLedBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox LeftLedBox()
        {
            return _LeftLedBox;
        }
        void LeftLedBox(::winrt::Microsoft::UI::Xaml::Controls::NumberBox value)
        {
            _LeftLedBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox RightLedBox()
        {
            return _RightLedBox;
        }
        void RightLedBox(::winrt::Microsoft::UI::Xaml::Controls::NumberBox value)
        {
            _RightLedBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox BottomLedBox()
        {
            return _BottomLedBox;
        }
        void BottomLedBox(::winrt::Microsoft::UI::Xaml::Controls::NumberBox value)
        {
            _BottomLedBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox StartPosBox()
        {
            return _StartPosBox;
        }
        void StartPosBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _StartPosBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox DirectionBox()
        {
            return _DirectionBox;
        }
        void DirectionBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _DirectionBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider RedGainSlider()
        {
            return _RedGainSlider;
        }
        void RedGainSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _RedGainSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider GreenGainSlider()
        {
            return _GreenGainSlider;
        }
        void GreenGainSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _GreenGainSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider BlueGainSlider()
        {
            return _BlueGainSlider;
        }
        void BlueGainSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _BlueGainSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider BrightnessSlider()
        {
            return _BrightnessSlider;
        }
        void BrightnessSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _BrightnessSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider SmoothingSlider()
        {
            return _SmoothingSlider;
        }
        void SmoothingSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _SmoothingSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ModeBox()
        {
            return _ModeBox;
        }
        void ModeBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ModeBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button SolidColorButton()
        {
            return _SolidColorButton;
        }
        void SolidColorButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _SolidColorButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox EffectBox()
        {
            return _EffectBox;
        }
        void EffectBox(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _EffectBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColorPicker StripColorPicker()
        {
            return _StripColorPicker;
        }
        void StripColorPicker(::winrt::Microsoft::UI::Xaml::Controls::ColorPicker value)
        {
            _StripColorPicker = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch MasterPowerToggle()
        {
            return _MasterPowerToggle;
        }
        void MasterPowerToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _MasterPowerToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StatusText()
        {
            return _StatusText;
        }
        void StatusText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StatusText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch StyleToggle()
        {
            return _StyleToggle;
        }
        void StyleToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _StyleToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch StartupToggle()
        {
            return _StartupToggle;
        }
        void StartupToggle(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _StartupToggle = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView _NavView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _HeaderTextBlock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _PowerPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _EffectsPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _MotionPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _ColorPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _MappingPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _HardwarePanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _SensorsPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _AboutPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _GpuTempText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar _GpuTempProgressBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _LdrValueText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar _LdrProgressBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ComPortBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _AuxModeBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColorPicker _AuxColorPicker{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox _TopLedBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox _LeftLedBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox _RightLedBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NumberBox _BottomLedBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _StartPosBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _DirectionBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _RedGainSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _GreenGainSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _BlueGainSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _BrightnessSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _SmoothingSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ModeBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _SolidColorButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _EffectBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColorPicker _StripColorPicker{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _MasterPowerToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StatusText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _StyleToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _StartupToggle{nullptr};
    };
}

