
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainWindow.xaml.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::AmbilightUI::implementation
{


    using Application = ::winrt::Microsoft::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Microsoft::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Microsoft::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Microsoft::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///MainWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 2:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NavigationView>();
                this->NavView(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NavigationView const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->NavView_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 3:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->HeaderTextBlock(targetElement);
            }
            break;
        case 4:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->PowerPanel(targetElement);
            }
            break;
        case 5:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->EffectsPanel(targetElement);
            }
            break;
        case 6:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->MotionPanel(targetElement);
            }
            break;
        case 7:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->ColorPanel(targetElement);
            }
            break;
        case 8:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->MappingPanel(targetElement);
            }
            break;
        case 9:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->HardwarePanel(targetElement);
            }
            break;
        case 10:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::StackPanel>();
                this->SensorsPanel(targetElement);
            }
            break;
        case 11:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->AboutPanel(targetElement);
            }
            break;
        case 12:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->GpuTempText(targetElement);
            }
            break;
        case 13:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ProgressBar>();
                this->GpuTempProgressBar(targetElement);
            }
            break;
        case 14:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->LdrValueText(targetElement);
            }
            break;
        case 15:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ProgressBar>();
                this->LdrProgressBar(targetElement);
            }
            break;
        case 16:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->ComPortBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ComPort_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 17:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->AuxModeBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->AuxMode_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 18:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColorPicker>();
                this->AuxColorPicker(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ColorChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::ColorPicker const& p0, ::winrt::Microsoft::UI::Xaml::Controls::ColorChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->AuxColor_ColorChanged(p0, p1);
                    }
                });
            }
            break;
        case 19:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NumberBox>();
                this->TopLedBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NumberBox const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NumberBoxValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LedBox_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 20:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NumberBox>();
                this->LeftLedBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NumberBox const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NumberBoxValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LedBox_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 21:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NumberBox>();
                this->RightLedBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NumberBox const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NumberBoxValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LedBox_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 22:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NumberBox>();
                this->BottomLedBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NumberBox const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NumberBoxValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LedBox_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 23:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->StartPosBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->StartPos_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 24:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->DirectionBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Direction_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 25:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->RedGainSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Slider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 26:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->GreenGainSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Slider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 27:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->BlueGainSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Slider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 28:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->BrightnessSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Slider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 29:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Slider>();
                this->SmoothingSlider(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ValueChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->Slider_ValueChanged(p0, p1);
                    }
                });
            }
            break;
        case 30:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->ModeBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ModeBox_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 31:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->SolidColorButton(targetElement);
            }
            break;
        case 32:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->EffectBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->EffectBox_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 33:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColorPicker>();
                this->StripColorPicker(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ColorChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::ColorPicker const& p0, ::winrt::Microsoft::UI::Xaml::Controls::ColorChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->StripColor_ColorChanged(p0, p1);
                    }
                });
            }
            break;
        case 34:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->MasterPowerToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->MasterPower_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 35:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->StatusText(targetElement);
            }
            break;
        case 36:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->StyleToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->StyleToggle_Toggled(p0, p1);
                    }
                });
            }
            break;
        case 37:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch>();
                this->StartupToggle(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Toggled([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->StartupToggle_Toggled(p0, p1);
                    }
                });
            }
            break;
        }
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }


    template <typename D, typename... I>
    IComponentConnector MainWindowT<D, I...>::GetBindingConnector(int32_t, IInspectable const&)
    {
        return nullptr;
    }

    template struct MainWindowT<struct MainWindow>;
}


#pragma warning(pop)


