// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_AmbilightUI_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::AmbilightUI::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::AmbilightUI
{
    MainWindow::MainWindow() :
        MainWindow(make<AmbilightUI::implementation::MainWindow>())
    {
    }
}
