// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_AmbilightUI_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::AmbilightUI::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::AmbilightUI
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<AmbilightUI::implementation::XamlMetaDataProvider>())
    {
    }
}
