// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_AmbilightUI_0_H
#define WINRT_AmbilightUI_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::AmbilightUI
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::AmbilightUI::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::AmbilightUI::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::AmbilightUI::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::AmbilightUI::MainWindow> = L"AmbilightUI.MainWindow";
    template <> inline constexpr auto& name_v<winrt::AmbilightUI::XamlMetaDataProvider> = L"AmbilightUI.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::AmbilightUI::IMainWindow> = L"AmbilightUI.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::AmbilightUI::IMainWindow>{ 0x6EE38686,0x8B96,0x5B0E,{ 0x9C,0x7F,0x70,0xF8,0x8D,0x01,0x62,0x12 } }; // 6EE38686-8B96-5B0E-9C7F-70F88D016212
    template <> struct default_interface<winrt::AmbilightUI::MainWindow>{ using type = winrt::AmbilightUI::IMainWindow; };
    template <> struct default_interface<winrt::AmbilightUI::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::AmbilightUI::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_AmbilightUI_IMainWindow
    {
    };
    template <> struct consume<winrt::AmbilightUI::IMainWindow>
    {
        template <typename D> using type = consume_AmbilightUI_IMainWindow<D>;
    };
}
#endif
